from typing import Final

class Tags:
    EXT : Final = "caption"
    EXT_WD14 : Final = f"{EXT}_wd14"
    EXT_BLIP : Final = f"{EXT}_blip"
    EXT_CROPPED : Final = f"{EXT}_cropped"
    EXT_PROCINFO : Final = f"{EXT}_procinfo"

    CELEB : Final = "rakhee thakar"
    CELEB2 : Final = "tifa_lockhart"
    CLASS : Final = "woman"
    CROPPED : Final = "cropped"
    SKIP : Final = "skipit"
    PROCINFO = [SKIP,]
    HEADER : Final = [CELEB2, CLASS,]
    FOOTER : Final = ["watermark", "indoors"]
    DEL : Final = [
        "1girl",
        "2girls",
        "couple",
        "1boy",
        "penis",
        "lactation",
        "urethra",
        "artist",
        "yuri",
        "pregnant",
        "mole",
        "username",
        "address",
    ]
    DEL_OLD : Final = [
        "solo",
        "1boy",
        "hetero",
        "topless",
        "plump",
        "looking at viewer",
        "smile",
        "ass",
        "anus",
        "penis",
        "armpits",
        "feet",
        "soles",
        "clitoris",
        "tifa",
        "denim",
        "pantyhose",
        "navel",
        "cleavage",
        "sitting",
        "standing",
        "kneeling",
        "squatting",
        "lying",
        "masturbation",
        "lactation",
        "erection",
        "clitoral",
        "urethra",
        "clothes",
        "artist",
        "toe",
        "toes",
        "belly",
        "nose",
        "finger",
        "fingers",
        "fingering",
        "cum",
        "bra",
        "panties",
        "thong",
        "areolae",
        "censoring",
        "sandals",
        "fours",
        "grin",
        "tank",
        "yuri",
        "glasses",
        "jewelry",
        "necklace",
        "miniskirt",
        "fishnets",
        "underwear",
        "lingerie",
        "lace",
        "dress",
        "shorts",
        "shirt",
        "skirt",
        "polka",
        "earrings",
        "makeup",
        "pregnant",
        "mole",
        "username",
        "address",
    ]
    DEL_KEY_OLD : Final = [
        "girl",
        "boy",
        "female",
        "body",
        "nude",
        "boob",
        "breast",
        "nipple",
        "nipples",
        "pussy",
        "hair",
        "mouth",
        "tongue",
        "teeth",
        "eyes",
        "hand",
        "lips",
        "legs",
        "thighs",
        "foot",
        "shoulders",
        "nail",
        "arms",
        "looking",
        "panties",
        "pants",
        "underwear",
        "leotard",
        "swimsuit",
        "bracelet",
        "earring",
        "shoe",
        "heel",
        "solo",
        "control",
        "censored",
    ]
    DEL_COLOR : Final = [
        "black",
        "white",
        "red",
        "green",
        "blue",
        "pink",
        "brown",
        "orange",
        "yellow",
        "blonde",
        "lace",
        "grey",
        "denim",
        "short",
        "tied",
    ]
    def __init__(self) -> None:
        pass