from typing import Final


class TaggerDef:
    LABEL_TBR: Final = '__tbr'
    LABELS: Final = {
        'label': [
            'body',
            'pussy',
            'ass',
            'breast',
            'face',
            'foot',
            'leg',
            'mouth',
            'hand',
            'thigh',
            'insert',
            'job',
            'step',
            LABEL_TBR,
        ],
        'interaction': ['in', 'front', 'none', LABEL_TBR],
        'trigger': ['1gts', '1hairy', '1legs', '1fbb', LABEL_TBR],
    }
    TAGS_CUSTOM: Final = {
        'bodypart': [
            'body',
            'pussy',
            'ass',
            'breast',
            'face',
            'foot',
            'leg',
            'mouth',
            'hand',
            'thigh',
            'penis',
            'insert',
            'job',
            '_step',
            '_penis',
            '+penis',
            '_1gts0',
            LABEL_TBR,
        ],
        'interaction': ['in', 'front', 'none', LABEL_TBR],
        'trigger': ['1gts', '1hairy', '1legs', '1fbb', LABEL_TBR],
    }
    TAGS_FOCUS: Final = {
        'realistic': 5469,
        'breasts': 5279,
        'large breasts': 4171,
        'standing': 4099,
        'smile': 4040,
        'thighs': 4013,
        'indoors': 3885,
        'full body': 3681,
        'looking at another': 3526,
        'open mouth': 3386,
        'muscular': 3278,
        'cleavage': 3121,
        'looking at viewer': 3061,
        'makeup': 3039,
        'photorealistic': 3023,
        'medium breasts': 2980,
        'thick thighs': 2692,
        'legs': 2572,
        'lipstick': 2540,
        'simple background': 2531,
        'nude': 2531,
        'high heels': 2489,
        'closed mouth': 2400,
        'parted lips': 2396,
        'sitting': 2393,
        'ass': 2369,
        'fingernails': 2356,
        'mini person': 2293,
        'male focus': 2262,
        'closed eyes': 2235,
        'feet': 2211,
        'teeth': 2087,
        'toes': 2075,
        'barefoot': 2056,
        'miniboy': 2049,
        'nipples': 2038,
        'nail polish': 2010,
        'completely nude': 1853,
        'from below': 1539,
        'holding': 1498,
        'lying': 1488,
        'from behind': 1483,
        'muscular female': 1467,
        'huge breasts': 1466,
        'looking down': 1395,
        'toenails': 1379,
        'pubic hair': 1314,
        'uncensored': 1264,
        'close-up': 1232,
        'penis': 1173,
        'pussy': 1105,
        'biceps': 1101,
        'outdoors': 1085,
        'on back': 1082,
        'female pubic hair': 974,
        'grin': 950,
        'upper body': 930,
        'leg hair': 923,
        'toned': 920,
        'bedroom': 920,
        'stomach': 901,
        'spread legs': 885,
        'on bed': 882,
        'censored': 851,
        'head out of frame': 838,
        'erection': 822,
        'tongue': 821,
        'anus': 816,
        'kneeling': 703,
        'ass focus': 683,
        'testicles': 681,
        'femdom': 624,
        'toenail polish': 616,
        'veiny arms': 615,
        'hairy': 566,
        'thighhighs': 557,
        'clothed female nude male': 552,
        'between breasts': 542,
        'pussy juice': 522,
        'tongue out': 506,
        'excessive pubic hair': 503,
        'looking up': 475,
        'sex': 456,
        'eye contact': 435,
        'armpit hair': 433,
        'on couch': 420,
        'foot focus': 402,
        'clitoris': 397,
        'masturbation': 385,
        'huge ass': 384,
        'lower body': 373,
        'walking': 359,
        'breasts apart': 346,
        'sideboob': 346,
        'armpits': 344,
        'sitting on person': 343,
        'anal hair': 338,
        'on stomach': 337,
        'cum': 331,
        'out of frame': 330,
        'lifting person': 329,
        'stepped on': 328,
        'perspective': 327,
        'vaginal': 323,
        'hands on own hips': 309,
        'carrying': 304,
        'spread pussy': 299,
        'bent over': 269,
        'cunnilingus': 256,
        'girl on top': 255,
        'gigantic breasts': 245,
        'bride': 226,
        'wedding': 226,
        'face to breasts': 226,
        'head between breasts': 223,
        'all fours': 222,
        'saliva': 220,
        'flexing': 218,
        'body hair': 206,
        'female masturbation': 201,
        'grabbing': 194,
        'ass grab': 191,
        'carrying person': 190,
        'licking': 189,
        'on one knee': 189,
        'breast smother': 184,
        'breast focus': 173,
        'anal': 172,
        'groom': 170,
        'ejaculation': 166,
        'fellatio': 158,
        'handjob': 147,
        'male masturbation': 146,
        'breast press': 124,
        'hand focus': 117,
        'pointing': 115,
        'anilingus': 114,
        'kiss': 111,
        'bondage': 89,
        'breast sucking': 87,
        'anus peek': 86,
        'orgasm': 83,
        'footjob': 78,
        "hand on another's thigh": 75,
        'dominatrix': 75,
        'black pubic hair': 74,
        'sex from behind': 59,
        'laughing': 58,
        'breastfeeding': 57,
        'object insertion': 54,
        'handsfree ejaculation': 44,
        'between legs': 41,
        'anal fingering': 30,
        'praying': 30,
        'hands on ass': 30,
        'whip': 27,
        'foot worship': 25,
    }
    TAGS_AVOID: Final = {
        '1girl': 0,
        '1boy': 0,
        'solo': 4522,
        'solo focus': 3147,
        'muscular male': 2545,
        'multiple boys': 1798,
        '2boys': 1430,
        'manly': 1192,
        'minigirl': 1148,
        'multiple girls': 1072,
        '2girls': 965,
        'statue': 509,
        'blood': 454,
        'horror (theme)': 439,
        'no humans': 427,
        'child': 360,
        'small breasts': 290,
        ':d': 256,
        'baby': 235,
        'fat man': 226,
        '1other': 226,
        '6+boys': 199,
        'incest': 188,
        'mother and son': 187,
        'doll': 159,
        '3boys': 140,
        'genderswap': 131,
        'death': 113,
        '3girls': 95,
        '6+girls': 81,
        '4boys': 67,
        'corpse': 58,
        'character doll': 56,
        '5boys': 47,
        '4girls': 41,
    }
    TAGS_AVOID_1GTS = [
        '1girl',
        'size difference',
        'giant',
        'mini person',
        'giantess',
        'miniboy',
        'multiple boys',
        '2boys',
        'height difference',
        'tall female',
        'minigirl',
        'multiple girls',
        '2girls',
        'giant male',
        'tall',
        'no humans',
        'child',
        '6+boys',
        'incest',
        '3boys',
        'genderswap',
        'figure',
        'father and daughter',
        '3girls',
        '6+girls',
        '4boys',
        'brother and sister',
        '5boys',
        '4girls',
    ]
